JTCMRMDictionary = {'Actin': ['IWHHTFYNELR', 'VAPEEHPVLLTEAPLNPK', 'TTGVVLDSGDGVTHTVPIYEGYALPHAILR', 'DLTDYLM[+16.0]K', 'GYSFTTTAER', 'SYELPDGQVITVGNER', 'DLYANTVLSGGTTMYPGIADR'],
                        'Rpl3' : ['SKPIHLTAFLGYK', 'ALTTIWAEHLSEEAR', 'AHLVEIQVNGGTIEQK', 'YGIVNQDYIMLR'],
                        'Tubulin' : ['SIFVDLEPTVVDEIR', 'IISQVVSSITASLR', 'YMAVC[+57.0]LLYR', 'AVC[+57.0]MLSNTTAIAEAWSR'],
                        'Calreticulin' : ['TLVIQYTVK', 'ADADLGDFHGETPYNVMFGPDIC[+57.0]GPTR', 'SGTIFDNIIITDSVEEAEAHAAETFDK'],
                        'EFT-2' : ['IWC[+57.0]FGPDGTGPNLLMDVTK', 'RVFYASVLTAEPR', 'LLEPVYLVEIQC[+57.0]PEAAVGGIYGVLNR', 'VFYASVLTAEPR', 'GHVFEESQVTGTPMFVVK'],
                        'GFP' : ['GEELFTGVVPILVELDGDVNGHK', 'FSVSGEGEGDATYGK', 'SAMPEGYVQER', 'TIFFKDDGNYK', 'FEGDTLVNR', 'GIDFKEDGNILGHK', 'LEYNYNSHNVYIMADK']
                        }
